### ISSUE TITLE
Missing symbol "g_dbus_proxy_new_for_bus" when launching google-chrome.

### ISSUE THREAD

**Issue by yeroc** [adamel/chrome-deps#2]
When I build and install this rpm I get the following error when trying to launch google-chrome:
```
$ google-chrome
/usr/bin/google-chrome: symbol lookup error: /usr/bin/google-chrome: undefined symbol: g_dbus_proxy_new_for_bus
```

Not sure if I'm somehow doing something wrong but looking at http://chrome.richardlloyd.org.uk/ it looks like the libgio-2.0 and libgobject-2.0 libraries also need to be extracted and included from the Fedora RPMs.

**Comment by adamel** [comment]
Ah, this was actually fixed in version 1.5, which unfortunately wasn't pushed to GitHub. Version 1.5 works fine for me with current CentOS 6 64-bit and Chrome 43.
